### ISSUE TITLE
Check time stamps and make sure they are in SL time. 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#184]

**Comment by jayasanka-sack** [comment]
@anupama-pathirage @AmilaJ Could you please fix this? I think the times are from different time zone.

**Comment by anupama-pathirage** [comment]
The reason to the issue is, that there are a few occurrences [1],[2],[3],[4]where we used UTC time as the updated timestamp.

[1]https://github.com/LSFLK/MedicinesforLK-AdminAPI/blob/main/db_processor.bal#L201
[2]https://github.com/LSFLK/MedicinesforLK-AdminAPI/blob/main/db_processor.bal#L203
[3] https://github.com/LSFLK/MedicinesforLK-AdminAPI/blob/main/db_processor.bal#L365
[4] https://github.com/LSFLK/MedicinesforLK-AdminAPI/blob/main/db_processor.bal#L367

@ThisaruGuruge Can you please check and update this to use local SL time ?

**Comment by ThisaruGuruge** [comment]
@anupama-pathirage Sure will do.

**Comment by nshamit** [comment]
Hi @anupama-pathirage @ThisaruGuruge 
I made a pledge this morning at around 11AM, but i'm seeing the time stamp incorrectly say 5 something AM. 

![Screen Shot 2022-07-28 at 11 38 25](https://user-images.githubusercontent.com/44461004/181432956-1f5db477-9191-4b90-a132-2283c50b853f.jpg)

**Comment by anupama-pathirage** [comment]
@ThisaruGuruge I think even we merged this PR we didn't deploy that fix yet in choreo.

**Comment by anupama-pathirage** [comment]
@nshamit Can u check now, thisaru's changes are now in production.

**Comment by nshamit** [comment]
Hi @anupama-pathirage Time stamps are still not working 

![Screen Shot 2022-07-29 at 10 42 34](https://user-images.githubusercontent.com/44461004/181687353-b3c09722-ce00-435e-88f5-545ab8bba8a5.jpg)

**Comment by anupama-pathirage** [comment]
@ThisaruGuruge Can you please investigate further?

**Comment by ThisaruGuruge** [comment]
I'll do an investigation and update.

**Comment by ThisaruGuruge** [comment]
This seems like an issue in the front-end. The Database stores the epoch value. Changing it might cause issues. It should be handled at the front end where the epoch is retrieved and converted to a human-readable format.

I will send a PR to revert the previous changes since they are not needed now.

**Comment by nshamit** [comment]
@ThisaruGuruge has the PR been sent? @jayasanka-sack @nipunsampath can we follow up on this please?

**Comment by ThisaruGuruge** [comment]
> @ThisaruGuruge has the PR been sent? @jayasanka-sack @dinuka-rp can we follow up on this please?

Hi, as I've mentioned already, this should be done in the front end, not the back end.

**Comment by dinuka-rp** [comment]
![image](https://user-images.githubusercontent.com/47103883/183439275-de5a4387-59ea-4f0a-b0ab-74cda942b3d4.png)

Request Endpoint: https://9d2b57ae-4349-44f2-971c-106ae09d244d-dev.e1-us-east-azure.choreoapis.dev/qmov/admin-api/1.0.0/aidpackages/126/updatecomments

@ThisaruGuruge The admin portal does not return timestamps as UNIX epoch times. The dateTime is returned as a string by the API. This should be returned as a 10-digit number, for the frontend to be able to convert it into the correct time.

**Comment by dinuka-rp** [comment]
Backend changes required @manuranga 

- [ ] The dateTime timestamp needs to be received as a number from the backend.
- [ ] The current Backend schema for upsert update comment (PUT Req) requires a dateTime variable. This won't be sent from the frontend. Therefore, it needs to be removed from the request body of the PUT request.
https://github.com/LSFLK/MedicinesforLK/pull/379#issuecomment-1209804566
